
unsigned long Current_Time_RF_Sensor_Scan;
unsigned long Previous_Time_RF_Sensor_Scan;
unsigned long Current_Time_Any_Incoming_Web_Request;
unsigned long Previosu_Time_Any_Incoming_Web_Request;
unsigned long Current_Time_Post_To_DataServer;
unsigned long Previous_Time_Post_To_DataServer;
unsigned long Current_Time_Post_To_Local_UDP;
unsigned long Previous_Time_Post_To_Local_UDP;

